/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  admin: {
    Feedback: () => import('#controllers/admin/feedback_controller'),
    Owners: () => import('#controllers/admin/owners_controller'),
    Plans: () => import('#controllers/admin/plans_controller'),
  },
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
  },
  client: {
    Booking: () => import('#controllers/client/booking_controller'),
    BookingPayment: () => import('#controllers/client/booking_payment_controller'),
    Property: () => import('#controllers/client/property_controller'),
  },
  Cron: () => import('#controllers/cron_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  proprio: {
    Booking: () => import('#controllers/proprio/booking_controller'),
    Client: () => import('#controllers/proprio/client_controller'),
    Expense: () => import('#controllers/proprio/expense_controller'),
    Feedback: () => import('#controllers/proprio/feedback_controller'),
    Finance: () => import('#controllers/proprio/finance_controller'),
    Profile: () => import('#controllers/proprio/profile_controller'),
    Property: () => import('#controllers/proprio/property_controller'),
    PropertyImage: () => import('#controllers/proprio/property_image_controller'),
    Report: () => import('#controllers/proprio/report_controller'),
    Residence: () => import('#controllers/proprio/residence_controller'),
    Subscription: () => import('#controllers/proprio/subscription_controller'),
  },
}
