/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/cloudinary.ts" />
/// <reference path="../../config/firebase.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
